[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[dependencies]
rwf = { git = "https://github.com/levkk/rwf.git", rev = "c946c7d" }
tokio = { version = "1", features = ["full"] }
comrak = "*"
rwf-admin = { git = "https://github.com/levkk/rwf.git", rev = "c946c7d" }
